services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - '8000:80'
    volumes:
      - ./backend:/var/www/html
    env_file:
      - ./backend/.env
    profiles:
      - backend
    depends_on:
      - db
      - mailpit

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sanctum_cookie
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    profiles:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    profiles:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vite_frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    command: npm run dev
    profiles:
      - frontend
    depends_on:
      - backend

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - '1025:1025'
      - '8025:8025'
    profiles:
      - mailpit

volumes:
  db_data:
