import { RouteObject } from 'react-router';
import App from './App';
import AuthCallback from './components/auth/components/AuthCallback';
import DatenschutzPage from './pages/DatenschutzPage';
import ErrorPage from './pages/ErrorPage';
import HomePage from './pages/HomePage';
import ImprintPage from './pages/ImprintPage';
import PlaygroundPage from './pages/PlaygroundPage';
import ResetPasswordPage from './pages/ResetPasswordPage';

const routes: RouteObject[] = [
    {
        path: '/',
        element: <App />,
        errorElement: <ErrorPage />,
        children: [
            { index: true, element: <HomePage /> },
            { path: 'playground', element: <PlaygroundPage /> },
            { path: 'impressum', element: <ImprintPage /> },
            { path: 'datenschutz', element: <DatenschutzPage /> },
        ],
    },
    {
        path: '/auth/callback',
        element: <AuthCallback />,
    },
    {
        path: '/reset-password', // This path must match the one generated by your Laravel backend
        element: <ResetPasswordPage />,
        errorElement: <ErrorPage />, // Optional: dedicated error page for this route
    },
];

export default routes;
